#!/usr/bin/env bash

# For main results
#python experiment/for_paper_plot.py --dir logs/thesis/vanilla/pickplace_dobot/pickplace/ logs/thesis/tderror/pickplace_dobot/pickplace/ logs/thesis/ebp/pickplace_dobot/pickplace/ logs/thesis/mep/pickandplace/ logs/thesis/ours/pickplace_dobot/pickplace/ --legend 'Vanilla' 'One-step ranking' 'EBP' 'MEP' 'Two-step ranking (Ours)' --range 200 --emphases 4
#python experiment/for_paper_plot.py --dir logs/thesis/vanilla/push_fetch/push/ logs/thesis/tderror/push_fetch/push/ logs/thesis/ebp/push_fetch/push/ logs/thesis/mep/push/ logs/thesis/ours/push_fetch/push --legend 'Vanilla' 'One-step ranking' 'EBP' 'MEP' 'Two-step ranking (Ours)' --range 200 --emphases 4
#python experiment/for_paper_plot.py --dir logs/thesis/vanilla/slide_fetch/slide/ logs/thesis/tderror/slide_fetch/slide/ logs/thesis/ebp/slide_fetch/slide/ logs/thesis/mep/slide/ logs/thesis/ours/slide_fetch/slide_use_per/ --legend 'Vanilla' 'One-step ranking' 'EBP' 'MEP' 'Two-step ranking (Ours)' --range 200 --ylim 0.6 --emphases 4
#python experiment/for_paper_plot.py --dir logs/thesis/vanilla/reach_dobot/reach/ logs/thesis/tderror/reach_dobot/reach/ logs/thesis/ours/reach_dobot/reach/ --legend 'Vanilla' 'One-step ranking' 'Two-step ranking (Ours)' --range 15 --emphases 2

# For ablation
#python experiment/for_paper_plot_ablation.py --dir logs/thesis/vanilla/reach_dobot/reach/ logs/thesis/ours/reach_dobot/reach_wo_ep/ logs/thesis/ours/reach_dobot/reach_wo_goal/ logs/thesis/ours/reach_dobot/reach/ --legend 'Vanilla' 'Ours (w/ prioritized episode)' 'Ours (w/ prioritized goal)' 'Ours (full)' --range 15 --emphases 3
#python experiment/for_paper_plot_ablation.py --dir logs/thesis/vanilla/pickplace_dobot/pickplace/ logs/thesis/ours/pickplace_dobot/pickplace_wo_goal/ logs/thesis/ours/pickplace_dobot/pickplace_wo_ep/ logs/thesis/ours/pickplace_dobot/pickplace/ --legend 'Vanilla' 'Ours (w/ prioritized episode)' 'Ours (w/ prioritized goal)' 'Ours (full)' --range 200 --emphases 3
#python experiment/for_paper_plot_ablation.py --dir logs/thesis/vanilla/push_fetch/push/ logs/thesis/ours/push_fetch/use_per_a8b5_wo_trans/ logs/thesis/ours/push_fetch/push_wo_eps/ logs/thesis/ours/push_fetch/push/ --legend 'Vanilla' 'Ours (w/ prioritized episode)' 'Ours (w/ prioritized goal)' 'Ours (full)' --range 200 --emphases 3
#python experiment/for_paper_plot_ablation.py --dir logs/thesis/vanilla/slide_fetch/slide/ logs/thesis/ours/slide_fetch/use_per_a6b4_wo_trans/ logs/thesis/ours/slide_fetch/use_per_a6b4_wo_eps/ logs/thesis/ours/slide_fetch/slide_use_per/ --legend 'Vanilla' 'Ours (w/ prioritized episode)' 'Ours (w/ prioritized goal)' 'Ours (full)' --range 200 --emphases 3 --ylim 0.6

# Generate final result
python experiment/for_paper_plot.py --dir logs/thesis/vanilla/slide_fetch/slide/ logs/thesis/tderror/slide_fetch/slide/ logs/thesis/ebp/slide_fetch/slide/ logs/thesis/mep/slide/ logs/thesis/ours/slide_fetch/slide_use_per/ --legend 'Vanilla' 'One-step ranking' 'EBP' 'MEP' 'Two-step ranking (Ours)' --range 200 --ylim 0.6 --emphases 4 --final_result True --smooth 0
python experiment/for_paper_plot.py --dir logs/thesis/vanilla/pickplace_dobot/pickplace/ logs/thesis/tderror/pickplace_dobot/pickplace/ logs/thesis/ebp/pickplace_dobot/pickplace/ logs/thesis/mep/pickandplace/ logs/thesis/ours/pickplace_dobot/pickplace/ --legend 'Vanilla' 'One-step ranking' 'EBP' 'MEP' 'Two-step ranking (Ours)' --range 300 --emphases 4 --final_result True --smooth 0
python experiment/for_paper_plot.py --dir logs/thesis/vanilla/push_fetch/push/ logs/thesis/tderror/push_fetch/push/ logs/thesis/ebp/push_fetch/push/ logs/thesis/mep/push/ logs/thesis/ours/push_fetch/push --legend 'Vanilla' 'One-step ranking' 'EBP' 'MEP' 'Two-step ranking (Ours)' --range 200 --emphases 4 --final_result True --smooth 0